name: CD - build & deploy to k8s

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU and Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }} # set this secret (or use GITHUB_TOKEN for public)

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/savannahshop:${{ github.sha }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Set kubeconfig (from secret)
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig
          kubectl config use-context $(kubectl config current-context)
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}

      - name: Deploy to Kubernetes (update image)
        run: |
          kubectl -n savannah apply -f k8s/
          # patch deployments to use new image
          kubectl -n savannah set image deployment/savannah-web savannah-web=ghcr.io/${{ github.repository_owner }}/savannahshop:${{ github.sha }} --record || true
          kubectl -n savannah set image deployment/savannah-celery savannah-celery=ghcr.io/${{ github.repository_owner }}/savannahshop:${{ github.sha }} --record || true
          kubectl -n savannah rollout status deployment/savannah-web --timeout=2m || true
