name: CI with Coverage

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: savannahshop_test
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports: ["5432:5432"]

      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports: ["6379:6379"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: python manage.py migrate
        env:
          DATABASE_URL: postgresql://test_user:test_pass@localhost:5432/savannahshop_test
          DJANGO_SECRET_KEY: "ci-test-secret-key-123"
          DJANGO_DEBUG: "True"

      - name: Run tests with coverage
        run: |
          coverage run manage.py test
          coverage report
          coverage html
        env:
          DATABASE_URL: postgresql://test_user:test_pass@localhost:5432/savannahshop_test
          REDIS_URL: redis://localhost:6379/0
          DJANGO_SECRET_KEY: "ci-test-secret-key-123"
          DJANGO_DEBUG: "True"

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: htmlcov/
          retention-days: 7
